apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
  labels:
    app: restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      imagePullSecrets:
        - name: registrycredentials
      containers:
      - name: restapi
        image: registry.gitlab.com/fiuba-memo2/ejemplos/restapi:0.0.2
        envFrom:
          - secretRef:
              name: apisecret
          - configMapRef:
              name: apiconfig
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "250Mi"
          cpu: "500m"
        livenessProbe:
          httpGet:
            path: /version
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
