apiVersion: v1
kind: ConfigMap
metadata:
  name: apiconfig
data:
  APP_MODE: production
  DATABASE_URL: postgresql://neondb_owner:4TAHVcL8tEdh@ep-young-boat-a58j9gkk.us-east-2.aws.neon.tech/neondb?sslmode=require
  LOG_LEVEL: info
  LOG_URL: https://endpoint4.collection.sumologic.com/receiver/v1/http/ZaVnC4dhaV3Q0q9J24SICwnOnPEZCABEbR8Mt9bQIWmiPuUABBF8l-Vgqk-jFR3ojlQySEes9kbWMR8Io9t1pXV0qIrf6hrbjYXeV5fd5vVu5fqcQc1Dig==
  PORT: "3000"
  CLIENT_ID: bff2e96176c4459aa1225e4349dc904d
  CLIENT_SECRET: 50c53bcc91f340d4873ab17382429fb4
