apiVersion: v1
kind: ConfigMap
metadata:
  name: apiconfig
data:
  APP_MODE: production
  DATABASE_URL: postgresql://neondb_owner:yLnokz6Ixt5a@ep-black-sun-a5x79i3q.us-east-2.aws.neon.tech/neondb?sslmode=require
  LOG_LEVEL: debug
  LOG_URL: https://endpoint4.collection.sumologic.com/receiver/v1/http/ZaVnC4dhaV2t5M3dhRZ7ZBuSQ0tjEjuXIrFq2n3iqRnXUXu-DTIWxzZOTYBwFDvlu0-GSKcZtzmF1l9Nwm56pHeGPUTCTb6Ecp1uixwJZG9pSbYM7eEJ_g==
  PORT: "3000"
